"""delete name field from users table

Revision ID: 52adae61cc3b
Revises: 5fc9a133585f
Create Date: 2025-10-28 14:56:04.392838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52adae61cc3b"
down_revision: Union[str, None] = "5fc9a133585f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
