[project]
name = "stream-origin"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "aiobotocore>=2.22.0",
    "fastapi>=0.115.12",
    "pydantic-settings>=2.9.1",
    "uvicorn>=0.34.2",
]

[tool.ruff]
line-length = 100
